package com.hbm_doors;
import java.util.*;
import com.hbm_doors.legacy.client.model.variant.*;
public class DoorVariants {
 public record Variant(String name,String model,boolean legacy,String skin) {
  public DoorModelSelection selection(){return legacy?DoorModelSelection.legacy():DoorModelSelection.modern(skin);}
 }
 public static List<Variant> forDoor(String id){return switch(id){
case "large_vehicle_door" -> List.of(new Variant("Standard","hbm_doors:block/doors/large_vehicle_door_modern",false,"default"),new Variant("Rad","hbm_doors:block/doors/large_vehicle_door_modern_rad",false,"rad"),new Variant("Clear","hbm_doors:block/doors/large_vehicle_door_modern_clean",false,"clear"),new Variant("Legacy","hbm_doors:block/doors/large_vehicle_door_legacy",true,"default"));
case "round_airlock_door" -> List.of(new Variant("Standard","hbm_doors:block/doors/round_airlock_door_modern",false,"default"),new Variant("Clean","hbm_doors:block/doors/round_airlock_door_modern_clean",false,"clean"),new Variant("Green","hbm_doors:block/doors/round_airlock_door_modern_green",false,"green"),new Variant("Legacy","hbm_doors:block/doors/round_airlock_door_legacy",true,"default"));
case "fire_door" -> List.of(new Variant("Standard","hbm_doors:block/doors/fire_door_modern",false,"default"),new Variant("Black","hbm_doors:block/doors/fire_door_modern_black",false,"black"),new Variant("Orange","hbm_doors:block/doors/fire_door_modern_orange",false,"orange"),new Variant("Trefoil","hbm_doors:block/doors/fire_door_modern_trefoil",false,"trefoil"),new Variant("Yellow","hbm_doors:block/doors/fire_door_modern_yellow",false,"yellow"),new Variant("Legacy","hbm_doors:block/doors/fire_door_legacy",true,"default"));
case "sliding_blast_door" -> List.of(new Variant("Standard","hbm_doors:block/doors/sliding_blast_door_modern",false,"default"),new Variant("Variant 1","hbm_doors:block/doors/sliding_blast_door_modern_variant1",false,"variant1"),new Variant("Variant 2","hbm_doors:block/doors/sliding_blast_door_modern_variant2",false,"variant2"),new Variant("Legacy","hbm_doors:block/doors/sliding_blast_door_legacy",true,"default"));
case "sliding_seal_door" -> List.of(new Variant("Standard","hbm_doors:block/doors/sliding_seal_door_modern",false,"default"),new Variant("Legacy","hbm_doors:block/doors/sliding_seal_door_legacy",true,"default"));
case "secure_access_door" -> List.of(new Variant("Standard","hbm_doors:block/doors/secure_access_door_modern",false,"default"),new Variant("Gray","hbm_doors:block/doors/secure_access_door_modern_gray",false,"gray"),new Variant("Black","hbm_doors:block/doors/secure_access_door_modern_black",false,"black"),new Variant("Yellow","hbm_doors:block/doors/secure_access_door_modern_yellow",false,"yellow"),new Variant("Legacy","hbm_doors:block/doors/secure_access_door_legacy",true,"default"));
case "qe_sliding_door" -> List.of(new Variant("Standard","hbm_doors:block/doors/qe_sliding_door_modern",false,"default"),new Variant("Legacy","hbm_doors:block/doors/qe_sliding_door_legacy",true,"default"));
case "qe_containment_door" -> List.of(new Variant("Standard","hbm_doors:block/doors/qe_containment_door_modern",false,"default"),new Variant("Trefoil","hbm_doors:block/doors/qe_containment_door_modern_trefoil",false,"trefoil"),new Variant("Trefoil Yellow","hbm_doors:block/doors/qe_containment_door_modern_trefoil_yellow",false,"trefoil_yellow"),new Variant("Legacy","hbm_doors:block/doors/qe_containment_door_legacy",true,"default"));
case "water_door" -> List.of(new Variant("Standard","hbm_doors:block/doors/water_door_modern",false,"default"),new Variant("Clean","hbm_doors:block/doors/water_door_clean",false,"clean"),new Variant("Legacy","hbm_doors:block/doors/water_door_legacy",true,"default"));
case "silo_hatch" -> List.of(new Variant("Default","hbm_doors:block/doors/silo_hatch",false,"default"));
case "silo_hatch_large" -> List.of(new Variant("Default","hbm_doors:block/doors/silo_hatch_large",false,"default"));
case "vault_door" -> List.of(new Variant("skin_101","hbm_doors:block/doors/vault_door_skin_101",false,"skin_101"),new Variant("Vault 87","hbm_doors:block/doors/vault_door_skin_87",false,"default"),new Variant("Vault 106","hbm_doors:block/doors/vault_door_skin_106",false,"skin_106"),new Variant("Vault 2","hbm_doors:block/doors/vault_door_skin_2",false,"skin_2"),new Variant("Vault 99","hbm_doors:block/doors/vault_door_skin_99",false,"skin_99"),new Variant("Vault 81","hbm_doors:block/doors/vault_door_skin_81",false,"skin_81"),new Variant("Vault 111","hbm_doors:block/doors/vault_door_skin_111",false,"skin_111"),new Variant("Legacy","hbm_doors:block/doors/vault_door",true,"default"));
case "cargo_door" -> List.of(new Variant("Default","hbm_doors:block/doors/cargo_door",false,"default"));
case "modular_blast_door" -> List.of(new Variant("Original 1.12","hbm_doors:block/doors/modular_blast_door",false,"default"));
default -> throw new IllegalArgumentException(id);};}}